sudo: required
dist: trusty
language: node_js
node_js:
  - 10.0

services:
  - docker

# addons:
# apt:
#   sources:
#     - google-chrome
#   packages:
#     - google-chrome-stable

before_script:
  # - "export CHROME_BIN=chromium-browser"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t apshuk17/docker-angular -f Dockerfile.dev .

script:
  - docker run apshuk17/docker-angular npm run coverage