sudo: required
dist: trusty
# language: node_js
# node_js:
#   - '7.7.4'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - docker build -t apshuk17/docker-angular -f Dockerfile.dev .

script:
  - docker run apshuk17/docker-angular npm run test --single-run