sudo: required
services:
  - docker

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t apshuk17/docker-angular -f Dockerfile.dev .

script:
  - docker run apshuk17/docker-angular npm run coverage